# Generated by Django 3.2.16 on 2022-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msb', '0002_auto_20221020_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='melding',
            name='msb_item_mutatieregels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
