# Generated by Django 3.2.16 on 2022-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_add_reaction_statusses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horecacsvexport',
            name='uploaded_file',
            field=models.FileField(upload_to='exports/%Y'),
        ),
    ]
